target("ModdingFramework_DLL")
    set_kind("shared")
    set_basename("modding_framework")
    use_wxwidgets()
    add_files("*.cpp")
    add_packages(
        "DLL_Injection",
        "Logging",
        "spdlog",
        "StringFormatting",
        "UserInterface"
    )
